### ISSUE TITLE
Counters not working correctly.

### ISSUE THREAD

**Issue by gautamnaman** [incubateind/gdtc-Day2#2]
@rexyagami please help.

Counters not working correctly which I need help fixing.

I fixed the top heading by centering it & also fixed the icons which were very big.

![image](https://user-images.githubusercontent.com/39316737/107140426-cbef8a80-6947-11eb-831b-fefcc1c22b7a.png)

**Comment by pranjalBhadu** [comment]
<img width="1440" alt="Screenshot 2021-02-07 at 1 38 54 PM" src="https://user-images.githubusercontent.com/63093079/107140706-f6dade00-6949-11eb-9696-84c404693070.png">

I have worked on this issue please assign it to me

**Comment by rexyagami** [comment]
@gautamnaman Look for this section in the HTML, you will find some wrong value placed in there, enter those values according to the label value. Good Luck

**Comment by gautamnaman** [comment]
@rexyagami @pranjalBhadu Fixed it:) Thanks.
