### ISSUE TITLE
Line spacing in multiple sections

### ISSUE THREAD

**Issue by arn4b** [incubateind/gdtc-Day2#35]
@kroy96 @rexyagami  The spacing between headings, subheadings and paragraphs in multiple sections is not present. 
![Screenshot 2021-02-07 165842](https://user-images.githubusercontent.com/60937304/107145145-c0ab5780-6965-11eb-9b12-4fead28b7c74.jpg)

**Comment by rexyagami** [comment]
@arn4b yes, you have to fix these bugs and achieve the final design.

**Comment by arn4b** [comment]
Yes sir, did them already, now going to open a PR, thanks a ton!
