### ISSUE TITLE
Progress bar values are not correct.

### ISSUE THREAD

**Issue by Swapnil8** [incubateind/gdtc-Day2#6]
The values of the progress bar are not filled with respect to their numeric values. 
@rexyagami Please help with the issue!
![image](https://user-images.githubusercontent.com/70998579/107141142-ed06aa00-694c-11eb-85dc-239e93414f84.png)

- Swapnil Mishra

**Comment by rexyagami** [comment]
@Swapnil8 Yes sure, you can see the HTML file and look out for this section in the code, you will find some wrong entry there, find it and fix it according to the label values. Good Luck

**Comment by Swapnil8** [comment]
@rexyagami Found the problem and rectified it! 
Will be closing this issue now,
Thank You.
