### ISSUE TITLE
Problem with the progress bar

### ISSUE THREAD

**Issue by AayushVyasKIIT** [incubateind/gdtc-Day2#7]
The progress bars aren't showing the 
correct progress area in the bar. @rexyagami 

![Screenshot 2021-02-07 140328](https://user-images.githubusercontent.com/70998175/107141213-58507c00-694d-11eb-9c6f-7d06ce557797.jpg)

**Comment by AayushVyasKIIT** [comment]
I tried searching for errors in JS file but nothing helped. @rexyagami

**Comment by AayushVyasKIIT** [comment]
[UPDATE]: Tried editing the HTML file, there were some wrong entries init. 

![Screenshot 2021-02-07 142917](https://user-images.githubusercontent.com/70998175/107141769-10335880-6951-11eb-8755-1beb0b8a717d.jpg)
@rexyagami

**Comment by rexyagami** [comment]
@AayushVyasKIIT Bravo :) Good Work
