### ISSUE TITLE
name heading

### ISSUE THREAD

**Issue by ankit-kumar18** [incubateind/gdtc-Day2#9]
I am trying to center both vertically and horizontally but only horizontally I can pull. can you help me with the how-to do vertical center? @kroy96

**Comment by rexyagami** [comment]
@ankit-kumar18 Hello, can you show me where you are doing this thing.

**Comment by ankit-kumar18** [comment]
> @ankit-kumar18 Hello, can you show me where you are doing this thing.

**Comment by ankit-kumar18** [comment]
> @ankit-kumar18 Hello, can you show me where you are doing this thing.

![Screenshot (115)](https://user-images.githubusercontent.com/76585167/107143962-fea47d80-695d-11eb-8e8e-4340cf73d59a.png)

**Comment by rexyagami** [comment]
for the first section?

**Comment by ankit-kumar18** [comment]
> for the first section?

completed. thank you
